language: android
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  # - tools
  # - platform-tools

  # The BuildTools version used by your project
  - build-tools-28.0.3

  # The SDK version used to compile your project
  - android-28

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  # - sys-img-x86-android-26
  # - sys-img-armeabi-v7a-android-17

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name Redwid
  - git config --local user.email $GIT_USER_EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  dry_run: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: '1.0.2'